deterministic_model:
  product_categories: { "erratic": 2, "smooth": 2, "intermittent": 2, "lumpy": 2}
  n_time_periods: 26
  joint_setup_cost: 2500
  minor_setup_ratio: 1.2
  service_level: 0.95
  should_include_safety_stock: True
  beta: 0.8
rl_model:
  n_products: 6
  n_time_periods: 52
  joint_setup_cost: 5000
  minor_setup_cost: [ 1000.0, 1000.0, 1000.0, 1000.0, 1000.0, 1000.0 ]
  holding_cost: [ 56.746590597921845, 27.808012422471087, 55.161044780561035, 57.072195025923534, 60.601173777486366, 17.492847296869314]
  shortage_cost: [ 140,  140,  140,  140,  140,  140 ]
  base_unit_cost: [ 71.5, 109.0, 8.49, 3.19, 65.55, 65.55 ]
  big_m: [ 100, 100, 100, 100, 100, 100 ]
  service_level: [ 0.95, 0.95, 0.95, 0.95 , 0.95 ,0.95 ]
  epsilon: [ 0.00001 ]
  shipping_cost: [ 500 ]
  lower_bound_free_shipping: [ 4500 ]
  should_include_safety_stock: True

main:
  should_analyse: False
  stationary_products: True
  generate_new_data: True
  seed: 2
simulation:
  forecasting_method: "holt_winter"
  verbose: False
  should_set_holding_cost_dynamically: True
  n_episodes: 100
  simulation_length: 52
  warm_up_length: 52
  should_perform_warm_up: True
  reset_length: 13
  should_write: True

environment:
  n_periods_historical_data: 2
  rolling_window_forecast: 5
  # Note: maximum_order_quantity / n_action_classes must be an integer
  n_action_classes: 15
  maximum_order_quantity: 105
  order_quantity_per_discrete_class: 5
  should_include_individual_forecast: True
  should_include_total_forecast: False
rl:
  method: "ppo"
  generate_data: True
