deterministic_model:
  product_categories: { "erratic": 4, "smooth": 4, "intermittent": 4, "lumpy": 4}
  n_time_periods: 13
  joint_setup_cost: 2500
  minor_setup_ratio: 1.2
  service_level: 0.95
  should_include_safety_stock: True
  beta: 1
rl_model:
  product_categories: { "erratic": 2, "smooth": 0, "intermittent": 0, "lumpy": 0 }
  n_time_periods: 13
  joint_setup_cost: 2500
  minor_setup_ratio: 2.4
  service_level: 0.95
  beta: 1
  method: "ddpg"
  generate_data: True
main:
  should_analyse: False
  stationary_products: True
  generate_new_data: True
  seed: 0
simulation:
  forecasting_method: "holt_winter"
  verbose: False
  should_set_holding_cost_dynamically: True
  n_episodes: 100
  simulation_length: 52
  warm_up_length: 52
  should_perform_warm_up: True
  reset_length: 13
  should_write: True

environment:
  n_periods_historical_data: 13
  rolling_window_forecast: 0
  # Note: maximum_order_quantity / n_action_classes must be an integer
  n_action_classes: 15
  maximum_order_quantity: 105
  order_quantity_per_discrete_class: 5
  should_include_individual_forecast: False
  should_include_total_forecast: False
  should_reset_at_each_episode: False

rl:
  method: "ppo"
  generate_data: True
