deterministic_model:
  n_products: 6
  n_time_periods: 13
  joint_setup_cost: 500
  minor_setup_cost: [ 100.0, 100.0, 100.0, 100.0, 100.0, 100.0 ]
  holding_cost: [ 7.15,7.15,7.15,7.15, 7.15, 7.15 ]
  shortage_cost: [ 140,  140,  140,  140,  140,  140 ]
  base_unit_cost: [ 71.5, 109.0, 8.49, 3.19, 65.55, 65.55 ]
  big_m: [ 100, 100, 100, 100, 100, 100 ]
  service_level: [ 0.95, 0.95, 0.95, 0.95 , 0.95 ,0.95]
  epsilon: [ 0.00001 ]
  shipping_cost: [ 500 ]
  lower_bound_free_shipping: [ 4500 ]
  should_include_safety_stock: True
main:
  should_analyse: False
  stationary_products: True
simulation:
  forecasting_method: "sarima"
  verbose: False
  should_set_holding_cost_dynamically: True